### ISSUE TITLE
Wiki Update Request: Add Q&A and Big-Picture Page in English

### ISSUE THREAD

**Issue by chienweiluo** [mouldjs/mould#34]
**What I've changed ?**

* Translate Big-Picture and Q&A Pages

    * Added 2 files [Q&A_en-US.md](https://github.com/chienweiluo/Mould-WIKI/blob/master/Q&A_en-US.md) and [Big-Picture_en-US.md](https://github.com/chienweiluo/Mould-WIKI/blob/master/Big-Picture_en-US.md)
    * [Repo here](https://github.com/chienweiluo/Mould-WIKI)

**Commits**:

1. 305065d docs(Q&A_en-US.md): add QA page english version
2. bccb290 docs(Big-Picture_en-US): add Big-Picture page English version
3. d9f4469 fix(Q&A_en-US): bolder the title
4. 8ad1640 doc(Big-Picture_en-US.md): add blank row
5. a7c83b1 docs(Q&A_en-US.md): add blank rows

**Reviewers**:
* @tuoxiansp

**Comment by tuoxiansp** [comment]
💯Thanks for the awesome work !
